version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5000"